import {
  EMR_ANGLEARC,
  EMR_ARC,
  EMR_ARCTO,
  EMR_ABORTPATH,
  EMR_CREATEPALETTE,
  EMR_BEGINPATH,
  EMR_BITBLT,
  EMR_CHORD,
  EMR_CLOSEFIGURE,
  EMR_COMMENT,
  EMR_CREATEBRUSHINDIRECT,
  EMR_CREATEDIBPATTERNBRUSHPT,
  EMR_CREATEPEN,
  EMR_ELLIPSE,
  EMR_ENDPATH,
  EMR_EOF,
  EMR_EXCLUDECLIPRECT,
  EMR_EXTCREATEFONTINDIRECTW,
  EMR_EXTCREATEPEN,
  EMR_EXTTEXTOUTA,
  EMR_EXTTEXTOUTW,
  EMR_EXTSELECTCLIPRGN,
  EMR_FILLRGN,
  EMR_PAINTRGN,
  EMR_POLYDRAW,
  EMR_FLATTENPATH,
  EMR_FILLPATH,
  EMR_HEADER,
  EMR_INTERSECTCLIPRECT,
  EMR_LINETO,
  EMR_MOVETOEX,
  EMR_MODIFYWORLDTRANSFORM,
  EMR_OFFSETCLIPRGN,
  EMR_POLYBEZIER,
  EMR_POLYBEZIER16,
  EMR_POLYBEZIERTO,
  EMR_POLYBEZIERTO16,
  EMR_POLYGON,
  EMR_POLYGON16,
  EMR_POLYLINE,
  EMR_POLYLINE16,
  EMR_POLYLINETO,
  EMR_POLYLINETO16,
  EMR_POLYPOLYGON,
  EMR_POLYPOLYGON16,
  EMR_POLYPOLYLINE,
  EMR_POLYPOLYLINE16,
  EMR_PIE,
  EMR_RECTANGLE,
  EMR_ROUNDRECT,
  EMR_REALIZEPALETTE,
  EMR_SCALEVIEWPORTEXTEX,
  EMR_SCALEWINDOWEXTEX,
  EMR_SELECTCLIPPATH,
  EMR_ALPHABLEND,
  EMR_MASKBLT,
  EMR_PLGBLT,
  EMR_SETARCDIRECTION,
  EMR_SETMETARGN,
  EMR_SETBKCOLOR,
  EMR_SETBKMODE,
  EMR_SETCOLORADJUSTMENT,
  EMR_SETICMMODE,
  EMR_SETICMPROFILEA,
  EMR_SETICMPROFILEW,
  EMR_SETLAYOUT,
  EMR_SETLINKEDUFIS,
  EMR_SETMAPMODE,
  EMR_SETMAPPERFLAGS,
  EMR_SETPIXELV,
  EMR_SETROP2,
  EMR_SELECTPALETTE,
  EMR_SETSTRETCHBLTMODE,
  EMR_SETBRUSHORGEX,
  EMR_SETMITERLIMIT,
  EMR_SETPOLYFILLMODE,
  EMR_SELECTOBJECT,
  EMR_SETTEXTJUSTIFICATION,
  EMR_SETWORLDTRANSFORM,
  EMR_STROKEANDFILLPATH,
  EMR_STROKEPATH,
  EMR_SETDIBITSTODEVICE,
  EMR_STRETCHBLT,
  EMR_STRETCHDIBITS,
  EMR_SETTEXTALIGN,
  EMR_SETTEXTCOLOR,
  EMR_TRANSPARENTBLT,
  EMR_GRADIENTFILL,
  EMR_SETVIEWPORTEXTEX,
  EMR_SETVIEWPORTORGEX,
  EMR_SETWINDOWEXTEX,
  EMR_SETWINDOWORGEX,
  EMR_WIDENPATH
} from '../../emf/constants.js'
import { buildCssFontFromLogFontW } from '../text-layout.js'

export {
  EMR_ANGLEARC,
  EMR_ARC,
  EMR_ARCTO,
  EMR_ABORTPATH,
  EMR_CREATEPALETTE,
  EMR_BEGINPATH,
  EMR_BITBLT,
  EMR_CHORD,
  EMR_CLOSEFIGURE,
  EMR_COMMENT,
  EMR_CREATEBRUSHINDIRECT,
  EMR_CREATEDIBPATTERNBRUSHPT,
  EMR_CREATEPEN,
  EMR_ELLIPSE,
  EMR_ENDPATH,
  EMR_EOF,
  EMR_EXCLUDECLIPRECT,
  EMR_EXTCREATEFONTINDIRECTW,
  EMR_EXTCREATEPEN,
  EMR_EXTTEXTOUTA,
  EMR_EXTTEXTOUTW,
  EMR_EXTSELECTCLIPRGN,
  EMR_FILLRGN,
  EMR_PAINTRGN,
  EMR_POLYDRAW,
  EMR_FLATTENPATH,
  EMR_FILLPATH,
  EMR_HEADER,
  EMR_INTERSECTCLIPRECT,
  EMR_LINETO,
  EMR_MOVETOEX,
  EMR_MODIFYWORLDTRANSFORM,
  EMR_OFFSETCLIPRGN,
  EMR_POLYBEZIER,
  EMR_POLYBEZIER16,
  EMR_POLYBEZIERTO,
  EMR_POLYBEZIERTO16,
  EMR_POLYGON,
  EMR_POLYGON16,
  EMR_POLYLINE,
  EMR_POLYLINE16,
  EMR_POLYLINETO,
  EMR_POLYLINETO16,
  EMR_POLYPOLYGON,
  EMR_POLYPOLYGON16,
  EMR_POLYPOLYLINE,
  EMR_POLYPOLYLINE16,
  EMR_PIE,
  EMR_RECTANGLE,
  EMR_ROUNDRECT,
  EMR_REALIZEPALETTE,
  EMR_SCALEVIEWPORTEXTEX,
  EMR_SCALEWINDOWEXTEX,
  EMR_SELECTCLIPPATH,
  EMR_SETARCDIRECTION,
  EMR_SETMETARGN,
  EMR_SETBKCOLOR,
  EMR_SETBKMODE,
  EMR_SETCOLORADJUSTMENT,
  EMR_SETICMMODE,
  EMR_SETICMPROFILEA,
  EMR_SETICMPROFILEW,
  EMR_SETLAYOUT,
  EMR_SETLINKEDUFIS,
  EMR_SETMAPMODE,
  EMR_SETMAPPERFLAGS,
  EMR_SETPIXELV,
  EMR_SETROP2,
  EMR_SELECTPALETTE,
  EMR_ALPHABLEND,
  EMR_MASKBLT,
  EMR_PLGBLT,
  EMR_SETSTRETCHBLTMODE,
  EMR_SETBRUSHORGEX,
  EMR_SETMITERLIMIT,
  EMR_SETPOLYFILLMODE,
  EMR_SELECTOBJECT,
  EMR_SETTEXTJUSTIFICATION,
  EMR_SETWORLDTRANSFORM,
  EMR_STROKEANDFILLPATH,
  EMR_STROKEPATH,
  EMR_SETDIBITSTODEVICE,
  EMR_STRETCHBLT,
  EMR_STRETCHDIBITS,
  EMR_SETTEXTALIGN,
  EMR_SETTEXTCOLOR,
  EMR_TRANSPARENTBLT,
  EMR_GRADIENTFILL,
  EMR_SETVIEWPORTEXTEX,
  EMR_SETVIEWPORTORGEX,
  EMR_SETWINDOWEXTEX,
  EMR_SETWINDOWORGEX,
  EMR_WIDENPATH
}
export { EmfPlusRecordType } from '../../emfplus/constants.js'

export const CREATE_PEN_WIDTH_OFFSET = 8
export const CREATE_PEN_COLOR_OFFSET = 16
export const CREATE_PEN_COLOR_FALLBACK_OFFSET = 12
export const EXT_CREATE_PEN_WIDTH_OFFSET = 24
export const EXT_CREATE_PEN_COLOR_OFFSET = 32
export const SMALL_POLY_POINT_COUNT_OFFSET = 16
export const SMALL_POLY_POINTS_OFFSET = 20
export const SMALL_POLY_POINT_SIZE = 4
export const SMALL_POLY_COUNTS_OFFSET = 24
export const MODIFY_WORLD_TRANSFORM_MODE_OFFSET = 24
export const MODIFY_WORLD_TRANSFORM_IDENTITY = 1
export const MODIFY_WORLD_TRANSFORM_LEFTMULTIPLY = 2
export const MODIFY_WORLD_TRANSFORM_RIGHTMULTIPLY = 3
export const MODIFY_WORLD_TRANSFORM_SET = 4
export const EMFPLUS_MATRIX_POSTMULTIPLY = 0x2000
export const EMFPLUS_WINDING_FILL = 0x2000
export const EMFPLUS_IMAGE_EFFECT = 0x2000
export const EMFPLUS_RELATIVE_POSITION = 0x0800
export const EMFPLUS_COMPRESSED = 0x4000
export const EMFPLUS_INLINE_COLOR = 0x8000
export const warnedUnknownObjects = new WeakSet()
export const EMFPLUS_DRIVER_STRING_CMAP_LOOKUP = 0x00000001
export const EMFPLUS_DRIVER_STRING_VERTICAL = 0x00000002
export const EMFPLUS_DRIVER_STRING_REALIZED_ADVANCE = 0x00000004
export const BACKGROUND_MODE_OPAQUE = 2
export const ETO_OPAQUE = 0x0002
export const ETO_PDY = 0x2000
export const CLIP_REGION_MODE_COPY = 5
export const CLIP_REGION_MODE_AND = 1
export const CLIP_REGION_MODE_OR = 2
export const CLIP_REGION_MODE_XOR = 3
export const CLIP_REGION_MODE_DIFF = 4
export const ARC_DIRECTION_COUNTERCLOCKWISE = 1
export const PEN_STYLE_MASK = 0x0000000f
export const PEN_ENDCAP_MASK = 0x00000f00
export const PEN_JOIN_MASK = 0x0000f000
export const PEN_STYLE_DASH = 0x00000001
export const PEN_STYLE_DOT = 0x00000002
export const PEN_STYLE_DASHDOT = 0x00000003
export const PEN_STYLE_DASHDOTDOT = 0x00000004
export const PEN_STYLE_NULL = 0x00000005
export const PEN_STYLE_USERSTYLE = 0x00000007
export const PEN_ENDCAP_SQUARE = 0x00000100
export const PEN_ENDCAP_FLAT = 0x00000200
export const PEN_JOIN_BEVEL = 0x00001000
export const PEN_JOIN_MITER = 0x00002000
export const BRUSH_STYLE_SOLID = 0x00000000
export const BRUSH_STYLE_NULL = 0x00000001
export const BRUSH_STYLE_HATCHED = 0x00000002
export const POINT_EPSILON = 1e-6

function createStockFont(faceName, height, weight = 400) {
  const font = {
    kind: 'font',
    faceName,
    height,
    escapement: 0,
    orientation: 0,
    weight,
    italic: false,
    underline: false,
    strikeOut: false
  }
  const css = buildCssFontFromLogFontW(font)

  return {
    ...font,
    css,
    cssFont: css
  }
}

export const STOCK_OBJECTS = new Map([
  [0x80000000, { kind: 'brush', color: 'rgb(255, 255, 255)' }],
  [0x80000001, { kind: 'brush', color: 'rgb(192, 192, 192)' }],
  [0x80000002, { kind: 'brush', color: 'rgb(128, 128, 128)' }],
  [0x80000003, { kind: 'brush', color: 'rgb(64, 64, 64)' }],
  [0x80000004, { kind: 'brush', color: 'rgb(0, 0, 0)' }],
  [0x80000005, { kind: 'brush', isNull: true }],
  [0x80000006, { kind: 'pen', color: 'rgb(255, 255, 255)', width: 1 }],
  [0x80000007, { kind: 'pen', color: 'rgb(0, 0, 0)', width: 1 }],
  [0x80000008, { kind: 'pen', isNull: true }],
  [0x8000000a, createStockFont('Terminal', 12, 400)],
  [0x8000000b, createStockFont('Courier New', 12, 400)],
  [0x8000000c, createStockFont('MS Sans Serif', 12, 400)],
  [0x8000000d, createStockFont('System', 16, 700)],
  [0x8000000e, createStockFont('System', 12, 400)],
  [0x8000000f, { kind: 'palette' }],
  [0x80000010, createStockFont('Courier New', 12, 400)],
  [0x80000011, createStockFont('MS Shell Dlg', 13, 400)],
  [0x80000012, { kind: 'brush', color: 'rgb(255, 255, 255)' }],
  [0x80000013, { kind: 'pen', color: 'rgb(0, 0, 0)', width: 1 }]
])

export const CLASSIC_DRAWING_RECORD_TYPES = new Set([
  EMR_ABORTPATH,
  EMR_ANGLEARC,
  EMR_ARC,
  EMR_ARCTO,
  EMR_BEGINPATH,
  EMR_BITBLT,
  EMR_CHORD,
  EMR_CLOSEFIGURE,
  EMR_ELLIPSE,
  EMR_ENDPATH,
  EMR_EXTTEXTOUTA,
  EMR_EXTTEXTOUTW,
  EMR_FILLPATH,
  EMR_LINETO,
  EMR_POLYBEZIER,
  EMR_PIE,
  EMR_POLYBEZIERTO,
  EMR_POLYGON,
  EMR_POLYBEZIER16,
  EMR_POLYBEZIERTO16,
  EMR_POLYLINE,
  EMR_POLYGON16,
  EMR_POLYLINE16,
  EMR_POLYLINETO,
  EMR_POLYLINETO16,
  EMR_POLYPOLYGON,
  EMR_POLYPOLYGON16,
  EMR_POLYPOLYLINE,
  EMR_POLYPOLYLINE16,
  EMR_RECTANGLE,
  EMR_ROUNDRECT,
  EMR_SELECTCLIPPATH,
  EMR_ALPHABLEND,
  EMR_MASKBLT,
  EMR_PLGBLT,
  EMR_SETPIXELV,
  EMR_STROKEANDFILLPATH,
  EMR_STROKEPATH,
  EMR_SETDIBITSTODEVICE,
  EMR_STRETCHBLT,
  EMR_STRETCHDIBITS,
  EMR_TRANSPARENTBLT,
  EMR_GRADIENTFILL
])

export function resolveClassicStockObject(handle) {
  return STOCK_OBJECTS.get(handle) ?? null
}

export function isClassicDrawingRecord(record) {
  return CLASSIC_DRAWING_RECORD_TYPES.has(record?.type)
}
